###
GET http://localhost:3000/sellers

###
GET http://localhost:3000/sellers/613d4a53dd5afa5e3726e9df

###
DELETE http://localhost:3000/sellers/613cda7656c960db8024f5f9
###
POST http://localhost:3000/sellers
Content-Type: application/json

{
"name":"Nimal",
"address":{"addressLine1":"12","addressLine2":"Street"},
"profileImage":"url",
"phone":"0111211111",
"email":"sdsds@gmail.com",
"itemsSelling":["613cef6968d3811759ef5017","613ceb0235f88d6f01c35cb4"],
"password":"123123"
}

###
POST http://localhost:3000/sellers/login
Content-Type: application/json

{
"name":"Nimal",
"email":"sdsds@gmail.com",
"password":"123123"
}

### 
PUT http://localhost:3000/sellers/613ced16ec8b4d5cc14f557d
Content-Type: application/json

{
"_id":"613cda7656c960db8024f5f9"
}

